name: Bug report
description: Reporte um problema na geração do HTML/PDF, parsing XML, ou layout.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reportar. Por favor, forneça informações suficientes para reproduzir.

  - type: input
    id: version
    attributes:
      label: Versão do pacote
      description: Ex.: 0.1.0
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: runtime
    attributes:
      label: Runtime/TFM
      options:
        - net48
        - netstandard2.0 (consumidor)
        - net6.0
        - net8.0
        - Outro
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Descrição do problema
      description: O que aconteceu e o que você esperava?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Passos para reproduzir
      description: Inclua um snippet mínimo. Se puder, anexe um XML (com dados sensíveis removidos).
      render: text
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs/Warnings
      description: Cole warnings retornados pela API ou stack trace.
      render: text
    validations:
      required: false

  - type: checkboxes
    id: privacy
    attributes:
      label: Privacidade
      options:
        - label: Confirmei que removi/anônimizei dados sensíveis (CNPJ/CPF, nomes, endereços).
          required: true
