name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write

jobs:
  pack-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Compute version from tag
        shell: pwsh
        run: |
          $tag = "${{ github.ref_name }}"     # ex: v0.1.1
          $ver = $tag.TrimStart("v")          # 0.1.1
          "PACKAGE_VERSION=$ver" | Out-File -FilePath $env:GITHUB_ENV -Append
          Write-Host "Version from tag: $ver"

      - name: Restore
        run: dotnet restore

      - name: Pack
        shell: pwsh
        run: dotnet pack src/Danfe/Danfe.csproj -c Release -o "$env:GITHUB_WORKSPACE\artifacts" /p:PackageVersion=$env:PACKAGE_VERSION

      - name: Nuget login (OIDC - temp API key)
        uses: NuGet/login@v1
        with:
          user: direction
          
      - name: Push to NuGet (OIDC)
        run: dotnet nuget push "$env:GITHUB_WORKSPACE\artifacts\*.nupkg" --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Push symbols (OIDC)
        run: dotnet nuget push "$env:GITHUB_WORKSPACE\artifacts\*.snupkg" --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/*.nupkg
            artifacts/*.snupkg
